version: '3.5'

services:
  admin:
    restart: always
    build:
      context: .
    ports:
      - "8888:80"
    volumes:
      - ./php:/var/www/html/php
      - ./public/admin/js:/var/www/html/public/admin/js
      - ./public/admin/index.php:/var/www/html/public/admin/index.php
      - ./public/admin/style.css:/var/www/html/public/admin/style.css
    environment:
      - TARANTOOL_TCP_NODELAY=1
      - TARANTOOL_DATABASE_QUERY=1
      - TARANTOOL_CONNECTIONS=tarantool:3301
    depends_on:
      - tarantool

  tarantool:
    image: "tarantool/tarantool:2"
    restart: always
    healthcheck:
      test: tarantool_is_up
      interval: 60s
      timeout: 15s
      retries: 10
